# Configuration file for the STM32 for VSCode extension
# Arrays can be inputted in two ways. One is: [entry_1, entry_2, ..., entry_final]
# or by adding an indented list below the variable name e.g.:
# VARIABLE:
# - entry_1
# - entry_2

# The project name
target: NUCLEO_F429ZI_AUTOCONFIG
# Can be C or C++
language: C

optimization: Og

# MCU settings
targetMCU: stm32f4x
cpu: cortex-m4 # type of cpu e.g. cortex-m4
fpu: fpv4-sp-d16 # Defines how floating points are defined. Can be left empty.
floatAbi: -mfloat-abi=hard
ldscript: STM32F429ZITx_FLASH.ld # linker script

# Compiler definitions. The -D prefix for the compiler will be automatically added.
cDefinitions: 
  - USE_HAL_DRIVER
  - STM32F429xx

cxxDefinitions: 
  - USE_HAL_DRIVER
  - STM32F429xx

asDefinitions: []

# Compiler definition files. you can add a single files or an array of files for different definitions.
# The file is expected to have a definition each new line.
# This allows to include for example a .definition file which can be ignored in git and can contain
# This can be convenient for passing along secrets at compile time, or generating a file for per device setup.
cDefinitionsFile:
cxxDefinitionsFile:
asDefinitionsFile:

# Compiler flags
cFlags: []
cxxFlags: []
assemblyFlags: []
linkerFlags: 
  - -specs=nano.specs


# libraries to be included. The -l prefix to the library will be automatically added.
libraries: 
  - c
  - m
  - nosys

# Library directories. Folders can be added here that contain custom libraries.
libraryDirectories: []

# Files or folders that will be excluded from compilation.
# Glob patterns (https://www.wikiwand.com/en/Glob_(programming)) can be used.
# Do mind that double stars are reserved in yaml
# these should be escaped with a: \ or the name should be in double quotes e.g. "**.test.**"
excludes: 
  - "**/Examples/**"
  - "**/examples/**"
  - "**/Example/**"
  - "**/example/**"
  - "**_template.*"


# Include directories (directories containing .h or .hpp files)
# If a CubeMX makefile is present it will automatically include the include directories from that makefile.
includeDirectories: 
  - Core/Inc
  - LWIP/App
  - LWIP/Target
  - Middlewares/Third_Party/LwIP/src/include
  - Middlewares/Third_Party/LwIP/system
  - Drivers/STM32F4xx_HAL_Driver/Inc
  - Drivers/STM32F4xx_HAL_Driver/Inc/Legacy
  - Middlewares/Third_Party/FreeRTOS/Source/include
  - Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS
  - Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F
  - Drivers/BSP/Components/lan8742
  - Middlewares/Third_Party/LwIP/src/include/netif/ppp
  - Drivers/CMSIS/Device/ST/STM32F4xx/Include
  - Middlewares/Third_Party/LwIP/src/include/lwip
  - Middlewares/Third_Party/LwIP/src/include/lwip/apps
  - Middlewares/Third_Party/LwIP/src/include/lwip/priv
  - Middlewares/Third_Party/LwIP/src/include/lwip/prot
  - Middlewares/Third_Party/LwIP/src/include/netif
  - Middlewares/Third_Party/LwIP/src/include/compat/posix
  - Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa
  - Middlewares/Third_Party/LwIP/src/include/compat/posix/net
  - Middlewares/Third_Party/LwIP/src/include/compat/posix/sys
  - Middlewares/Third_Party/LwIP/src/include/compat/stdc
  - Middlewares/Third_Party/LwIP/system/arch
  - Drivers/CMSIS/Include
  - Inc/**
  - Core/Inc/**
  - Core/Lib/**
  - Src/**
  - Core/Src/**
  - Core/Lib/**


# Files that should be included in the compilation.
# If a CubeMX makefile is present it will automatically include the  c and cpp/cxx files from that makefile.
# Glob patterns (https://www.wikiwand.com/en/Glob_(programming)) can be used.
# Do mind that double stars are reserved in yaml
# these should be escaped with a: \ or the name should be in double quotes e.g. "HARDWARE_DRIVER*.c"
sourceFiles:  
  - startup_stm32f429xx.s
  - Core/Src/main.c
  - Core/Src/freertos.c
  - Core/Src/stm32f4xx_it.c
  - Core/Src/stm32f4xx_hal_msp.c
  - Core/Src/stm32f4xx_hal_timebase_tim.c
  - LWIP/Target/ethernetif.c
  - LWIP/App/lwip.c
  - Drivers/BSP/Components/lan8742/lan8742.c
  - Drivers/BSP/Components/lan8742/lan8742.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c
  - Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c
  - Core/Src/system_stm32f4xx.c
  - Middlewares/Third_Party/FreeRTOS/Source/croutine.c
  - Middlewares/Third_Party/FreeRTOS/Source/event_groups.c
  - Middlewares/Third_Party/FreeRTOS/Source/list.c
  - Middlewares/Third_Party/FreeRTOS/Source/queue.c
  - Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c
  - Middlewares/Third_Party/FreeRTOS/Source/tasks.c
  - Middlewares/Third_Party/FreeRTOS/Source/timers.c
  - Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c
  - Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c
  - Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/auth.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/ccp.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/chap_ms.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/chap-md5.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/chap-new.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/demand.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/eap.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/eui64.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/fsm.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/ipcp.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/ipv6cp.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/lcp.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/magic.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/mppe.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/multilink.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/ppp.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/pppapi.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/pppcrypt.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/pppoe.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/pppol2tp.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/pppos.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/upap.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/utils.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/vj.c
  - Middlewares/Third_Party/LwIP/src/netif/bridgeif.c
  - Middlewares/Third_Party/LwIP/src/netif/bridgeif_fdb.c
  - Middlewares/Third_Party/LwIP/src/netif/ethernet.c
  - Middlewares/Third_Party/LwIP/src/netif/lowpan6.c
  - Middlewares/Third_Party/LwIP/src/netif/lowpan6_ble.c
  - Middlewares/Third_Party/LwIP/src/netif/lowpan6_common.c
  - Middlewares/Third_Party/LwIP/src/netif/slipif.c
  - Middlewares/Third_Party/LwIP/src/netif/zepif.c
  - Middlewares/Third_Party/LwIP/src/netif/ppp/ecp.c
  - Middlewares/Third_Party/LwIP/src/api/api_lib.c
  - Middlewares/Third_Party/LwIP/src/api/api_msg.c
  - Middlewares/Third_Party/LwIP/src/api/err.c
  - Middlewares/Third_Party/LwIP/src/api/if_api.c
  - Middlewares/Third_Party/LwIP/src/api/netbuf.c
  - Middlewares/Third_Party/LwIP/src/api/netdb.c
  - Middlewares/Third_Party/LwIP/src/api/netifapi.c
  - Middlewares/Third_Party/LwIP/src/api/sockets.c
  - Middlewares/Third_Party/LwIP/src/api/tcpip.c
  - Middlewares/Third_Party/LwIP/src/core/altcp.c
  - Middlewares/Third_Party/LwIP/src/core/altcp_alloc.c
  - Middlewares/Third_Party/LwIP/src/core/altcp_tcp.c
  - Middlewares/Third_Party/LwIP/src/core/def.c
  - Middlewares/Third_Party/LwIP/src/core/dns.c
  - Middlewares/Third_Party/LwIP/src/core/inet_chksum.c
  - Middlewares/Third_Party/LwIP/src/core/init.c
  - Middlewares/Third_Party/LwIP/src/core/ip.c
  - Middlewares/Third_Party/LwIP/src/core/mem.c
  - Middlewares/Third_Party/LwIP/src/core/memp.c
  - Middlewares/Third_Party/LwIP/src/core/netif.c
  - Middlewares/Third_Party/LwIP/src/core/pbuf.c
  - Middlewares/Third_Party/LwIP/src/core/raw.c
  - Middlewares/Third_Party/LwIP/src/core/stats.c
  - Middlewares/Third_Party/LwIP/src/core/sys.c
  - Middlewares/Third_Party/LwIP/src/core/tcp.c
  - Middlewares/Third_Party/LwIP/src/core/tcp_in.c
  - Middlewares/Third_Party/LwIP/src/core/tcp_out.c
  - Middlewares/Third_Party/LwIP/src/core/timeouts.c
  - Middlewares/Third_Party/LwIP/src/core/udp.c
  - Middlewares/Third_Party/LwIP/src/core/ipv4/autoip.c
  - Middlewares/Third_Party/LwIP/src/core/ipv4/dhcp.c
  - Middlewares/Third_Party/LwIP/src/core/ipv4/etharp.c
  - Middlewares/Third_Party/LwIP/src/core/ipv4/icmp.c
  - Middlewares/Third_Party/LwIP/src/core/ipv4/igmp.c
  - Middlewares/Third_Party/LwIP/src/core/ipv4/ip4.c
  - Middlewares/Third_Party/LwIP/src/core/ipv4/ip4_addr.c
  - Middlewares/Third_Party/LwIP/src/core/ipv4/ip4_frag.c
  - Middlewares/Third_Party/LwIP/src/core/ipv6/dhcp6.c
  - Middlewares/Third_Party/LwIP/src/core/ipv6/ethip6.c
  - Middlewares/Third_Party/LwIP/src/core/ipv6/icmp6.c
  - Middlewares/Third_Party/LwIP/src/core/ipv6/inet6.c
  - Middlewares/Third_Party/LwIP/src/core/ipv6/ip6.c
  - Middlewares/Third_Party/LwIP/src/core/ipv6/ip6_addr.c
  - Middlewares/Third_Party/LwIP/src/core/ipv6/ip6_frag.c
  - Middlewares/Third_Party/LwIP/src/core/ipv6/mld6.c
  - Middlewares/Third_Party/LwIP/src/core/ipv6/nd6.c
  - Middlewares/Third_Party/LwIP/system/OS/sys_arch.c
  - Middlewares/Third_Party/LwIP/src/apps/mqtt/mqtt.c
  - Src/**
  - Core/Src/**
  - Core/Lib/**


# When no makefile is present it will show a warning pop-up.
# However when compilation without the CubeMX Makefile is desired, this can be turned of.
suppressMakefileWarning: false

# Custom makefile rules
# Here custom makefile rules can be added to the STM32Make.make file
# an example of how this can be used is commented out below.
customMakefileRules:
# - command: sayhello
#   rule: echo "hello"
#   dependsOn: $(BUILD_DIR)/$(TARGET).elf # can be left out    
    