#DATABASE: C:\Users\Paul\Desktop\diplomka\PSCM_7Fold_STA3\test_connections.accdb
#DATA_FOLDER: C:\Users\Paul\Desktop\diplomka\PSCM_7Fold_STA3\original_files\

DATABASE: C:\Users\Filip\Desktop\diplomka\PSCM_7Fold_STA3\test_connections.accdb
DATA_FOLDER: C:\Users\Filip\Desktop\diplomka\PSCM_7Fold_STA3\original_files\